### ISSUE TITLE
Controls for novapi arm servos

### ISSUE THREAD

**Issue by NETtoSan** [NETtoSan/Makex-sources#4]
Would it be easier to control arms using the right joystick?
Move all surface controls to the left and remove fine control on the left buttons

**Comment by NETtoSan** [comment]
test

**Comment by knilios** [comment]
This is a comment!
Hello world

**Comment by knilios** [comment]
Wow, this is very cool!

**Comment by knilios** [comment]
I'm getting FUN

**Comment by knilios** [comment]
lol

**Comment by knilios** [comment]
Man, I really feel sorry for the person in charge of this.

**Comment by NETtoSan** [comment]
keep chat relevant lmao

**Comment by vaporform** [comment]
In my opinion, I would use the D-Pad to control the arms since the cubes are on a fixed height.

Using Up-Down directions to control the arm's movement should work alright.


( P.S. Can you send the arena's blueprints? )

**Comment by NETtoSan** [comment]
Adding the ability to raise the arm body up/down to a certain height would bring us with both strategic and tactical advantage. Since we can pick up the cube on the ground. And place it in a metal shaft.

However. It is very difficult to come by. As seen from other school's attempt, they almost killed their DC motor and their servos due to excessive weight. And inability to accurately measure LiPo's current voltage. (Which is best operated > 3.6V / cell)

**Comment by NETtoSan** [comment]
> In my opinion, I would use the D-Pad to control the arms since the cubes are on a fixed height.
> 
> Using Up-Down directions to control the arm's movement should work alright.
> 
> ( P.S. Can you send the arena's blueprints? )

@netwests 
https://www.makeblock.in.th/wp-content/uploads/2022/03/2022-season-makex-challenge-energy-innovator-rules-guide-v1.01.pdf

**Comment by vaporform** [comment]
> > In my opinion, I would use the D-Pad to control the arms since the cubes are on a fixed height.
> > 
> > Using Up-Down directions to control the arm's movement should work alright.
> > 
> > ( P.S. Can you send the arena's blueprints? )
> 
> @netwests 
> https://www.makeblock.in.th/wp-content/uploads/2022/03/2022-season-makex-challenge-energy-innovator-rules-guide-v1.01.pdf

@NETtoSan 
Thanks, highly appreciated!

**Comment by vaporform** [comment]
> Adding the ability to raise the arm body up/down to a certain height would bring us with both strategic and tactical advantage. Since we can pick up the cube on the ground. And place it in a metal shaft.

> 
> However. It is very difficult to come by. As seen from other school's attempt, they almost killed their DC motor and their servos due to excessive weight. And inability to accurately measure LiPo's current voltage. (Which is best operated > 3.6V / cell)

Can the arm's weights be lifted with 2 servos? Our robot "can" sustain their arm's weight by only using one servo albeit slightly.

But one problem arises; would the arm's length exceed the max dimensions?

I can see the potential to use the DC to control the arm's height. Maybe attaching it to a rail would work? If so, we can use the DC to easily surpass the dimensions rule.

**Comment by NETtoSan** [comment]
The servos have built-in overload protection system. If the overload reached its limit (Eg. 5Amps being drawn to do something) It shuts itself down and require a hard reset on that servo.

It's best to use a DC motor and at least 2 conveyor belts to compensate with the arm and the cubes weight

**Comment by NETtoSan** [comment]
> But one problem arises; would the arm's length exceed the max dimensions?

The dimension we put the arm on should not exceed 50cm iirc.

**Comment by vaporform** [comment]
> It's best to use a DC motor and at least 2 conveyor belts to compensate with the arm and the cubes weight

If I understand correctly, are you thinking about suspending the hand to a belt?

> The dimension we put the arm on should not exceed 50cm.

If we are using the servos for handling the arms, it would be very hard to avoid.

**Comment by netwests** [comment]
> The dimension we put the arm on should not exceed 50cm.

If we are using the servos for handling the arms, it would be very hard to avoid.

**Comment by NETtoSan** [comment]
> If I understand correctly, are you thinking about suspending the hand to a belt?

Yes 😅

**Comment by vaporform** [comment]
> Yes 😅

Honestly, It might work!
I was thinking about doing this for our robot too but I wouldn't trust the DC or the belt **too** much.

If we are planning to do this route; we have to find a way to make the hands lighter or add more support.

**Comment by NETtoSan** [comment]
> I was thinking about doing this for our robot too. But I wouldn't trust the DC or the belt too much.

If you are planning to use one. Don't use the 200rpm one. The speed is too much and low torque (if there's a torque difference at all). It will drain your batteries like hell

Add suspended metal rods between the arm to help stabilize the arm

**Comment by NETtoSan** [comment]
Heck we aren't doing this tomorrow xD

We will go there on Saturday and Sunday. We will observe the other team's techniques and apply it to our own

**Comment by vaporform** [comment]
> Add suspended metal rods between the arm to help stabilize the arm module 

And maybe use zip ties to hold the hands in place? I fear that the belt isn't that strong anyways.

> Heck we aren't doing this tomorrow xD

One night miracle always work! 👍

**Comment by netwests** [comment]
> Heck we aren't doing this tomorrow xD

One night miracle always work! 👍

**Comment by NETtoSan** [comment]
> > Heck we aren't doing this tomorrow xD
> 
> One night miracle always work! 👍

hahahaha
